name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: "Build and test code"
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] # We will add more in the future
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM and Clang (ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-19-dev clang-19 libclang-19-dev

      - name: Install Zig
        uses: mlugg/setup-zig@v2 # This uses the latest version.

      - name: Build
        run: zig build

      - name: Run 'factorial' example
        run: zig build -Dexamples factorial
